import type { Metadata } from "next";
import "./globals.css";
import { Roboto, Jura } from "next/font/google";
import BcvRateProviderServer from "./BcvRateProvider.server";
import Header from "./components/Header";
import { ThemeToggle } from "./utils/ThemeToggle";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  display: "swap",
  weight: ["500"],
});
const jura = Jura({
  variable: "--font-jura",
  subsets: ["latin"],
  display: "swap",
  weight: ["300"],
});

export const metadata: Metadata = {
  title: "NorbShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es">
      <body
        className={`${roboto.variable} ${jura.variable} antialiased  relative
      bg-gradient-to-br from-blue-100 via-purple-100 to-pink-100 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900`}
      >
        <BcvRateProviderServer>
          <div className="fixed hidden z-30 md:block top-2.5 right-14">
            <ThemeToggle />
          </div>
          <Header />
          {children}
        </BcvRateProviderServer>
      </body>
    </html>
  );
}
