import type { Metadata } from "next";
import "./globals.css";
import { Inconsolata, Roboto, Quicksand, Jura, Sen} from "next/font/google";

const quicksand = Quicksand({
  variable:'--font-quicksand',
  subsets:['latin'],
  display: 'swap',
  weight: ['700']
})

//         MONOSPACE
export const inconsolata = Inconsolata({
  variable: "--font-Inconsolata",
  subsets: ['latin'],
  display: 'swap',
  weight: ['600'],
});
//          NORMAL
export const roboto = Roboto ({
  variable: "--font-roboto",
  subsets: ['latin'],
  display: 'swap',
  weight: ['500']
})
//           LIGHT
export const jura = Jura ({
  variable: '--font-jura',
  subsets:['latin'],
  display: 'swap',
  weight:['300']
})
export const sen = Sen({
  variable: '--font-sen',
  subsets: ['latin'],
  display: 'swap',
  weight: ['800']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${quicksand.className} ${inconsolata.variable} ${roboto.variable} ${jura.variable}
      ${sen.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}